### ISSUE TITLE
Asking questions

### ISSUE THREAD

**Issue by yushangakki** [sloisel/pyptex#1]
Hi! I saw this program on reddit **r/math** and I tried to use this by the example, this is a great program! However, I want to ask a few quesitons:
- I am a neovim/vim user, is it possible to integrate `pyptex` into `latexmk` or  `pdflatex` so that the users can have a better experience by using `pyptex` along with the current editor extensions?
- When I execute `pyptex`, there would be a folder called `{$filename}-generated`. If I try to write a lot of documents it would be annoying. Is it possible to add other configurations so that the pictures generated by the program would be put in a certain place (like `~/Pictures`)? Thank you!

**Comment by sloisel** [comment]
Thank you for your kind feedback and intriguing feature requests.
* I'm afraid I must admit I've never used latexmk, although it looks rather amazing. Because of that, I don't know how to resolve the latexmk question.
* I'm not sure what you mean by integrating pyptex into pdflatex. In principle, with the --shell-escape command, you can call any shell command from pdflatex, including pyptex or Python, but if this what you want, other packages might suit you better, for example PythonTex. I call this a Python embedding into LaTeX. I used PythonTex last year, and PypTeX exists because I wanted not to use an embedding. I guess what I'm saying is, if you want to embed Python into LaTeX, use one of the other packages (SageTex, PythonTex, etc...)
* You don't have to use the {$filename}-generated folder, you can put your pictures anywhere you want. If you don't use it, it will be empty after pyptex run, so you could do `pyptex file.tex; rm -rf` file-generated when you build. It might be possible to put a command-line option so that the directory is only created if you need it, I'll keep that in mind for later. If it does happen, it may not take the shape of a command-line option for various reasons. In PypTeX, command-line options are a slightly delicate question, so I opted to put most configuration-type information as plain-old Python statements in your main.tex file. For example, switching the LaTeX interpreter is not done by command-line but rather via `@{pyp.latex="xelatex"}` in your `main.tex` file, so that's how any sort of `-generated/` directory tweaking might end up happening.

**Comment by sloisel** [comment]
So I apologize if I'm misusing github here but I don't quite know how to handle github issues. On the other hand, I'm not sure I have a concrete action item from your comment. What I'm going to do is, close the issue for now but if you feel like something needs to be addressed, either reopen it or make a new one later?

Thanks again for the useful feedback! :)
